### ISSUE TITLE
GNOME compatibility

### ISSUE THREAD

**Issue by manuel-uberti** [lassekongo83/stilo-themes#1]
Hi, 

first of all thanks for another set of wonderful themes. I've been using your `amber-theme` for quite a while, but recently I switched to `Stiloetto` (GTK) and `Stilo` (GNOME Shell).

Note that this is not an issue, just a note from enthusiastic user. In the README, you wrote:

```
It's possible that some parts of the theme will work with earlier versions. No fixes will however be made for earlier versions.
```

I am on Ubuntu 18.04.2 with GNOME 3.28.3, and everything looks gorgeous already. 

If, for the sake of completeness, you want to have the themes tested on this version of GNOME (no earlier than 3.28, to be more precise), do let me know. I'll be glad to try the themes and report back any issues I may find, saving you the time to check on 3.28 while working of 3.30+.

Do as you see fit, of course, I have always `amber-theme` to switch back to in case you break something. ;)

Keep up the great work!

**Comment by lassekongo83** [comment]
Sounds good. I try to keep it as close to upstream Adwaita as possible, with some compatibility fixes from Yaru. Any new fixes from upstream may break on older versions, as new classes and elements are added. If any compatibility fix for older versions break on newer versions, then I'll have to pass fixing that. So I can't always guarantee 3.28 support as time goes on.
