### ISSUE TITLE
Empty new line in right-click menu

### ISSUE THREAD

**Issue by manuel-uberti** [lassekongo83/stilo-themes#12]
### Describe the issue

When in Files, right-clicking on a directory opens a contextual menu. There is an empty new line after the last entry (`Properties`) in this menu.

I don't know if it is intended.

### Screenshot(s)

![Screenshot from 2020-07-01 13-27-38](https://user-images.githubusercontent.com/8199224/86239083-ee921780-bb9e-11ea-9b59-400767af90d4.png)

### Versions

Ubuntu 20.04 LTS
GNOME Shell 3.36.1 (x11)
GTK+ Version 3.24.18, cairo version 1.16.0

**Comment by lassekongo83** [comment]
See: https://gitlab.gnome.org/GNOME/gtk/-/issues/1996

**Comment by manuel-uberti** [comment]
Thank you for the link.
