### ISSUE TITLE
Sound indicator

### ISSUE THREAD

**Issue by manuel-uberti** [lassekongo83/stilo-themes#4]
With latest `Stiloetto` (GTK) / `Stilo` (GNOME Shell), I have this when I hit the volume buttons on my laptop keyboard:

![screenshot](https://user-images.githubusercontent.com/8199224/56860701-c5259c80-6999-11e9-85b3-275b7eac349d.png)

The bar indicating the volume level under the speaker "icon" looks a bit too dark to be readable. I don't know if this is only a problem with my screen (Dell XPS 13), or my eyes (short-sighted, sometimes I don't trust my eyes).

Nothing really serious, I can tell the volume level by the bars beside the speaker.

**Comment by lassekongo83** [comment]
Let me know if it's fixed. In have no way of testing those indicators.

**Comment by manuel-uberti** [comment]
Yes, fantastic. Thank you.
