### ISSUE TITLE
Add a compact version 

### ISSUE THREAD

**Issue by jilen** [lassekongo83/stilo-themes#5]
![Screenshot from 2019-04-28 17-31-29](https://user-images.githubusercontent.com/546573/56862251-831d4a80-69db-11e9-9307-b402a4b57558.png)

I mean make the title bar smaller.

**Comment by lassekongo83** [comment]
I have to keep it to a limit. A minimum of 38px on the toolbar/titlebar-combo seems work with most font configurations. Any smaller and new issues will arise.

**Comment by moriel5** [comment]
Would it be feasible to add a compact variant?
