### ISSUE TITLE
White shadow of popup

### ISSUE THREAD

**Issue by jilen** [lassekongo83/stilo-themes#6]
White shadow of popup 
![Screenshot from 2019-05-05 19-22-15](https://user-images.githubusercontent.com/546573/57193186-3f8e8780-6f6b-11e9-8e33-8b1989c01bcc.png)

**Comment by lassekongo83** [comment]
In which application? GTK version?

**Comment by jilen** [comment]
gnome shell, calendar and ibus cjk input popup
